# Generated by Django 5.0.7 on 2024-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.URLField()),
                ('details_json', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EntitiesMaster',
                'verbose_name_plural': 'EntitiesMasters',
                'ordering': ['-created_date'],
            },
        ),
    ]
